Repository swcamp9thTeam1/frontend-project-accountbook, pull requests merged in 2024-09, with the labels that each got.

#6 Header 및 초기화면 완성하였습니다.
  package-lock.json
  src/App.vue
  src/assets/icons/back-logo.svg
  src/assets/icons/check.svg
  src/assets/icons/kakao-icon.svg
  src/components/AppHeader.vue
  src/views/WelcomePage.vue
Labels: enhancement

#10 가계부 컴포넌트 일부 생성
  package-lock.json
  package.json
  src/assets/icons/가계부_가게입력_돋보기_이미지.svg
  src/assets/icons/가계부_검색_버튼.svg
  src/assets/icons/가계부_셀렉트박스_화살표.svg
  src/assets/icons/가계부_작성란_line.svg
  src/assets/icons/가계부_추가_버튼.svg
  src/assets/icons/가계부_카테고리관리_버튼.svg
  src/components/AccountBookInsert.vue
  src/components/AccountBookList.vue
  src/views/MyPage.vue
Labels: enhancement

#12 Feature/accbook/calander
  package-lock.json
  package.json
  src/components/AccountBookList.vue
  src/components/accbook/AccountBookDays.vue
  src/components/accbook/AccountBookInsert.vue
  src/components/accbook/AccountBookList.vue
  src/components/accbook/AccountBookListButtons.vue
  src/components/calendar/CustomCalendarView.vue
  src/components/calendar/CustomCalendarViewHeader.vue
  src/components/calendar/accbook-detail.json
  src/components/calendar/accbook-monthly-eval.json
  src/components/calendar/accbook-monthly.json
  src/router/router.js
  src/views/AccountBookPage.vue
  src/views/accountbook/AccbookAddView.vue
  src/views/accountbook/AccbookAllListView.vue
  src/views/accountbook/AccbookDailyListView.vue
  src/views/accountbook/AccbookDetailView.vue
Labels: enhancement

#13 Feature/component/hyeonjin
  src/assets/icons/button-close.svg
  src/assets/icons/button-read-more.svg
  src/assets/icons/marker-good-store.svg
  src/assets/icons/search.svg
  src/components/GoodStoreBox.vue
  src/components/ReadMoreButton.vue
  src/components/SaveMapMarkerCategoryList.vue
  src/components/SearchAddress.vue
  src/components/SearchAddressResult.vue
  src/components/SearchBar.vue
  src/components/StoreDetailModal.vue
  src/data/good-stores.json
  src/views/SaveMapPage.vue
Labels: enhancement

#15 마이페이지 회원정보 조회 페이지 구현
  src/components/MyPageSideMenu.vue
  src/views/MyPage.vue
Labels: enhancement

#19 마이페이지 사이드메뉴 생성
  src/components/Confirm.vue
  src/components/SideMenu.vue
  src/login/login-data.json
  src/router/router.js
  src/views/LoginPage.vue
  src/views/MyPage.vue
  src/views/SignupPage.vue
  src/views/my/MyAssetView.vue
  src/views/my/MyExpendView.vue
  src/views/my/MyReviewView.vue
  src/views/my/MyScrapView.vue
  src/views/my/MyWriteView.vue
Labels: enhancement

#26 로그인 및 사이드메뉴 수정
  src/components/AppHeader.vue
  src/components/SideMenu.vue
  src/components/useAuth.js
  src/views/LoginPage.vue
Labels: enhancement

#28 Feature/accbook/detail
  src/assets/icons/calendar-next-month.svg
  src/assets/icons/calendar-previous-month.svg
  src/components/accbook/AccountBookDetail.vue
  src/components/accbook/AccountBookList.vue
  src/components/calendar/CustomCalendarView.vue
  src/components/calendar/CustomCalendarViewHeader.vue
  src/data/mockup.json
  src/views/accountbook/AccbookDetailView.vue
Labels: enhancement

#29 Feature/accbook/detail router
  src/components/accbook/AccountBookDetail.vue
  src/components/accbook/AccountBookInsert.vue
  src/components/accbook/AccountBookList.vue
  src/router/router.js
  src/views/accountbook/AccbookDetailView.vue
Labels: enhancement

#30 FIX: 가계부 내역 컴포넌트 클릭 이벤트 변경
  src/components/accbook/AccountBookList.vue
  src/views/accountbook/AccbookAllListView.vue
Labels: enhancement

#32 [커뮤니티] 나의 글 / 로컬 스토리지 / 사이드메뉴 수정
  src/assets/icons/Community/CheckIcon.svg
  src/assets/icons/Community/CommentProfileIcon.svg
  src/assets/icons/Community/NextIcon.svg
  src/assets/icons/Community/PlusIcon.svg
  src/assets/icons/Community/SelectToggleIcon.svg
  src/components/AppHeader.vue
  src/components/SideMenu.vue
  src/components/useAuth.js
  src/data/mockup.json
  src/router/router.js
  src/views/CommunityPage.vue
  src/views/LoginPage.vue
  src/views/SignupPage.vue
  src/views/community/CommunityMyView.vue
  src/views/community/CommunityPostDetailView.vue
Labels: enhancement

#33 FIX: 가계부 상세조회 컴포넌트에 props 추가
  src/components/accbook/AccountBookDetail.vue
  src/router/router.js
  src/views/accountbook/AccbookDetailView.vue
Labels: enhancement

#34 Feature/save map
  package-lock.json
  src/assets/icons/button-back.svg
  src/assets/icons/button-plus.svg
  src/assets/icons/marker-cost-avg.svg
  src/assets/icons/marker-visited.svg
  src/assets/icons/next.svg
  src/assets/icons/previous.svg
  src/components/StoreDetailModal.vue
  src/components/buttons/ReadMoreButton.vue
  src/components/buttons/UploadImageButton.vue
  src/components/forms/WriteReviewInput.vue
  src/components/forms/WriteReviewTextarea.vue
  src/components/savemap/CostAvgChip.vue
  src/components/savemap/GoodStoreBox.vue
  src/components/savemap/ReviewChip.vue
  src/components/savemap/SaveMapMarkerCategoryList.vue
  src/components/savemap/SearchAddress.vue
  src/components/savemap/SearchAddressResult.vue
  src/components/savemap/SearchBar.vue
  src/components/savemap/StoreAccBookListView.vue
  src/components/savemap/StoreDetailModal.vue
  src/components/savemap/StoreReviewBox.vue
  src/components/savemap/StoreReviewListView.vue
  src/components/savemap/WriteReviewView.vue
  src/data/good-stores.json
  src/data/mockup.json
  src/views/SaveMapPage.vue
Labels: enhancement

#36 마이페이지 - 회원정보 조회, 나의 자산 조회
  package-lock.json
  package.json
  src/components/MyPageSideMenu.vue
  src/components/myPage/MyAssetList.vue
  src/components/myPage/MyPageEditInfo.vue
  src/components/myPage/MyPageInfo.vue
  src/data/mockup.json
  src/router/router.js
  src/views/MyPage.vue
  src/views/group/GroupSignUpStatus.vue
  src/views/my/MyAssetView.vue
  src/views/my/MyExpendView.vue
  src/views/my/MyInfoEditView.vue
  src/views/my/MyInfoPage.vue
  src/views/my/MyReviewView.vue
  src/views/my/MyScrapView.vue
  src/views/my/MyWriteView.vue
Labels: enhancement

#38 Community branch
  src/data/community-post.json
  src/views/CommunityPage.vue
  src/views/community/CommunityFreeBoardView.vue
  src/views/community/CommunityMyView.vue
  src/views/community/CommunityScrapView.vue
Labels: enhancement

#39 이전에 누락된 내용 push
  src/components/myPage/MyAssetList.vue
  src/components/myPage/MyPageEditInfo.vue
  src/components/myPage/MyPageInfo.vue
  src/router/router.js
  src/views/my/MyAssetView.vue
Labels: bug

#40 스크랩 버튼 기능 구현, 폰트 수정
  index.html
  src/views/CommunityPage.vue
  src/views/community/CommunityFreeBoardView.vue
Labels: enhancement

#41 마이페이지 뷰 수정, 자산 등록 페이지 추가
  src/components/SideMenu.vue
  src/components/myPage/MyAssetList.vue
  src/components/myPage/MyPageInfo.vue
  src/router/router.js
  src/views/my/AssetAddView.vue
  src/views/my/MyAssetView.vue
  src/views/my/MyInfoEditView.vue
  src/views/my/MyInfoPage.vue
  src/views/my/MyInfoView.vue
Labels: enhancement

#44 Feature/accbook/create post
  src/components/accbook/AccountBookCreate.vue
  src/components/accbook/AccountBookListButtons.vue
  src/components/calendar/CustomCalendarView.vue
  src/data/account-book.json
  src/data/mockup.json
  src/router/router.js
  src/views/AccountBookPage.vue
  src/views/accountbook/AccbookAddView.vue
  src/views/accountbook/AccbookAllListView.vue
  src/views/accountbook/AccbookDailyListView.vue
  src/views/accountbook/AccbookDetailView.vue
Labels: enhancement

#45 자산 삭제 페이지 및 기능 구현
  src/components/myPage/MyAssetList.vue
  src/data/mockup.json
  src/views/my/MyAssetView.vue
Labels: enhancement

#48 Feature/group/board
  src/App.vue
  src/assets/icons/ic-triangle-down-purple.svg
  src/components/Comment.vue
  src/components/CommentList.vue
  src/components/accbook/AccountBookDetail.vue
  src/components/group/GroupMemberAccBookList.vue
  src/components/group/GroupPostDetailView.vue
  src/data/mockup.json
  src/router/router.js
  src/views/group/GroupAccBook.vue
  src/views/group/GroupCommunityDetail.vue
Labels: enhancement

#50 자산 추가 기능 구현
  src/views/my/AssetAddView.vue
Labels: enhancement

#55 Community branch
  src/data/mockup.json
  src/router/router.js
  src/views/CommunityPage.vue
  src/views/community/CommunityCreatePostView.vue
  src/views/community/CommunityFreeBoardView.vue
  src/views/community/CommunityMyView.vue
  src/views/community/CommunityPostDetailView.vue
  src/views/community/CommunityScrapView.vue
Labels: enhancement

#56 나의 스크랩 페이지 구현
  src/data/mockup.json
  src/views/community/CommunityFreeBoardView.vue
  src/views/community/CommunityMyView.vue
  src/views/community/CommunityScrapView.vue
Labels: enhancement

#58 마이페이지 - 내가 스크랩한 글 목록 조회 페이지 추가
  src/components/myPage/MyAssetList.vue
  src/views/community/CommunityFreeBoardView.vue
  src/views/community/CommunityScrapView.vue
  src/views/my/MyScrapView.vue
Labels: enhancement

#61 Feature/mypage/mypost
  src/router/router.js
  src/views/my/MyWriteDetailView.vue
  src/views/my/MyWriteView.vue
Labels: enhancement

#62 스타일 요소 추가, 나의 게시글 수정 삭제 버튼 구현
  src/router/router.js
  src/views/community/CommunityCreatePostView.vue
  src/views/community/CommunityFreeBoardView.vue
  src/views/community/CommunityPostDetailView.vue
Labels: enhancement

#63 FEATURE: 캘린더 css 변경
  src/components/calendar/CustomCalendarView.vue
  src/components/calendar/CustomCalendarViewHeader.vue
  src/views/AccountBookPage.vue
Labels: enhancement

#64 [마이페이지] 나의 정기지출 추가, 수정, 삭제
  src/views/my/AddExpendView.vue
  src/views/my/DeleteExpendView.vue
  src/views/my/ModifyExpendView.vue
  src/views/my/MyExpendView.vue
Labels: enhancement

#66 Feature/my/review
  src/App.vue
  src/assets/icons/ic-arrow-back.svg
  src/assets/icons/ic-store-category-fd6.svg
  src/assets/icons/ic-success.svg
  src/components/buttons/UploadImageButton.vue
  src/components/modal/SuccessMessageModal.vue
  src/components/myPage/ReviewContentItem.vue
  src/components/myPage/ReviewDetailModal.vue
  src/components/myPage/StoreCategoryIcon.vue
  src/components/savemap/StoreDetailModal.vue
  src/data/mockup.json
  src/router/router.js
  src/utils/dialogManager.js
  src/views/SaveMapPage.vue
  src/views/my/MyReviewAddView.vue
  src/views/my/MyReviewView.vue
Labels: enhancement

#68 Feature/accbook/acc delete
  src/assets/icons/accbook-middle-line.svg
  src/components/accbook/AccountBookDetail.vue
  src/views/AccountBookPage.vue
Labels: enhancement

#69 자잘한 수정사항
  src/App.vue
  src/components/AppFooter.vue
  src/components/AppHeader.vue
  src/data/mockup.json
  src/router/router.js
  src/views/my/MyAssetView.vue
Labels: bug

#70 FIX: 그룹 페이지 레이아웃 조정
  src/App.vue
  src/views/GroupPage.vue
Labels: enhancement

#71 FEATURE: monthly-eval 데이터 수정
  src/data/mockup.json
Labels: documentation

#72 마이페이지 나의 정기 지출 router.js 수정
  src/router/router.js
Labels: enhancement

#73 정기지출 등록/수정 시 자산 불러와서 선택하는 기능
  src/components/SideMenu.vue
  src/data/mockup.json
  src/views/my/AddExpendView.vue
  src/views/my/ModifyExpendView.vue
Labels: enhancement

#74 FEATURE: 커뮤니티 게시글 작성 수정
  src/views/community/CommunityCreatePostView.vue
Labels: bug

#75 Update README.md
  README.md
Labels: documentation

#77 커뮤니티 나의글&자유게시판 내림차순 정렬 / 월예산 추가
  src/components/SideMenu.vue
  src/data/mockup.json
  src/views/SignupPage.vue
  src/views/community/CommunityFreeBoardView.vue
  src/views/community/CommunityMyView.vue
Labels: enhancement

#78 Update README.md
  README.md
Labels: documentation

#81 그룹 사이드 메뉴 추가 및 수정하였습니다.
  src/App.vue
  src/components/SideMenu.vue
  src/views/GroupPage.vue
  src/views/group/GroupPosts.vue
Labels: enhancement

#79 Update README.md
  README.md
Labels: documentation

#83 Update README.md
  README.md
Labels: documentation

#82 Update README.md
  README.md
Labels: documentation

#84 Update README.md
  README.md
Labels: documentation

#85 Update README.md
  README.md
Labels: documentation

#88 회원 정보 데이터 불러오는 부분 수정
  src/data/mockup.json
  src/views/my/MyAssetView.vue
  src/views/my/MyInfoEditView.vue
  src/views/my/MyInfoView.vue
Labels: enhancement

#87 스크랩 시 인덱스 추가
  src/data/mockup.json
  src/views/community/CommunityScrapView.vue
Labels: enhancement

#89 Update README.md
  README.md
Labels: documentation

#90 Update README.md
  README.md
Labels: documentation

#91 Update README.md
  README.md
Labels: documentation

#92 Update README.md
  README.md
Labels: documentation

#94 사이드 메뉴 오류 수정 / 정기지출 css 수정
  src/components/SideMenu.vue
  src/views/community/CommunityFreeBoardView.vue
  src/views/community/CommunityScrapView.vue
  src/views/my/MyExpendView.vue
Labels: enhancement

#95 Update README.md
  README.md
Labels: documentation

#98 Update README.md
  README.md
Labels: documentation

#99 Community branch
  src/assets/icons/Community/CommentProfileIcon copy.svg
  src/data/mockup.json
  src/router/router.js
  src/views/CommunityPage.vue
  src/views/community/CommunityFreeBoardView.vue
  src/views/community/CommunityPostDetailView.vue
Labels: enhancement

#97 사이드 메뉴 수정
  src/components/SideMenu.vue
Labels: enhancement

#104 Update README.md
  README.md
Labels: documentation

#105 FIX: /users api 사용하도록 가계부 페이지 수정
  src/data/mockup.json
  src/views/AccountBookPage.vue
Labels: enhancement
